import type { CatalogEntry } from "./types";

/**
 * Catalogue voitures — prix neuf catalogue France au lancement (TTC, € ronds).
 * Couverture : marques majoritaires sur le marché FR + sportives iconiques.
 * Les MSRP sont approximatifs, l'utilisateur peut ajuster avant sauvegarde.
 */
export const CAR_CATALOG: CatalogEntry[] = [
  // ========= Peugeot =========
  { id: "peugeot-108-active", brand: "Peugeot", model: "108", trim: "Active", category: "car", segment: "citadine", yearStart: 2014, yearEnd: 2021, msrpEur: 11500, fuel: "essence", power: 72 },
  { id: "peugeot-208-active-ii", brand: "Peugeot", model: "208 II", trim: "Active", category: "car", segment: "citadine", yearStart: 2019, msrpEur: 18500, fuel: "essence", power: 75 },
  { id: "peugeot-208-allure-ii", brand: "Peugeot", model: "208 II", trim: "Allure", category: "car", segment: "citadine", yearStart: 2019, msrpEur: 21000, fuel: "essence", power: 100 },
  { id: "peugeot-208-gt-ii", brand: "Peugeot", model: "208 II", trim: "GT", category: "car", segment: "citadine", yearStart: 2019, msrpEur: 26500, fuel: "essence", power: 130 },
  { id: "peugeot-e208-allure", brand: "Peugeot", model: "e-208", trim: "Allure", category: "car", segment: "citadine", yearStart: 2020, msrpEur: 33500, fuel: "elec", power: 136 },
  { id: "peugeot-208-gti-i", brand: "Peugeot", model: "208 GTi", category: "car", segment: "sportive", yearStart: 2013, yearEnd: 2019, msrpEur: 26500, fuel: "essence", power: 208 },
  { id: "peugeot-2008-allure-ii", brand: "Peugeot", model: "2008 II", trim: "Allure", category: "car", segment: "suv-compact", yearStart: 2019, msrpEur: 27500, fuel: "essence", power: 130 },
  { id: "peugeot-2008-gt-ii", brand: "Peugeot", model: "2008 II", trim: "GT", category: "car", segment: "suv-compact", yearStart: 2019, msrpEur: 33000, fuel: "essence", power: 155 },
  { id: "peugeot-308-allure-iii", brand: "Peugeot", model: "308 III", trim: "Allure", category: "car", segment: "compacte", yearStart: 2021, msrpEur: 31500, fuel: "essence", power: 130 },
  { id: "peugeot-308-gt-iii", brand: "Peugeot", model: "308 III", trim: "GT", category: "car", segment: "compacte", yearStart: 2021, msrpEur: 36500, fuel: "phev", power: 180 },
  { id: "peugeot-308-gti-ii", brand: "Peugeot", model: "308 GTi", category: "car", segment: "sportive", yearStart: 2015, yearEnd: 2021, msrpEur: 38500, fuel: "essence", power: 270 },
  { id: "peugeot-3008-allure-ii", brand: "Peugeot", model: "3008 II", trim: "Allure", category: "car", segment: "suv-compact", yearStart: 2016, yearEnd: 2023, msrpEur: 33500, fuel: "essence", power: 130 },
  { id: "peugeot-3008-gt-ii", brand: "Peugeot", model: "3008 II", trim: "GT", category: "car", segment: "suv-compact", yearStart: 2016, yearEnd: 2023, msrpEur: 41500, fuel: "phev", power: 225 },
  { id: "peugeot-3008-gt-iii", brand: "Peugeot", model: "3008 III", trim: "GT", category: "car", segment: "suv-compact", yearStart: 2024, msrpEur: 47000, fuel: "hybride", power: 136 },
  { id: "peugeot-5008-allure-ii", brand: "Peugeot", model: "5008 II", trim: "Allure", category: "car", segment: "suv-large", yearStart: 2017, yearEnd: 2024, msrpEur: 36500, fuel: "essence", power: 130 },
  { id: "peugeot-508-gt-ii", brand: "Peugeot", model: "508 II", trim: "GT", category: "car", segment: "berline", yearStart: 2018, msrpEur: 47500, fuel: "phev", power: 225 },
  { id: "peugeot-rcz", brand: "Peugeot", model: "RCZ", category: "car", segment: "sportive", yearStart: 2010, yearEnd: 2015, msrpEur: 32000, fuel: "essence", power: 200 },

  // ========= Renault =========
  { id: "renault-twingo-iii-zen", brand: "Renault", model: "Twingo III", trim: "Zen", category: "car", segment: "citadine", yearStart: 2014, yearEnd: 2024, msrpEur: 13500, fuel: "essence", power: 70 },
  { id: "renault-clio-v-zen", brand: "Renault", model: "Clio V", trim: "Zen", category: "car", segment: "citadine", yearStart: 2019, msrpEur: 18000, fuel: "essence", power: 75 },
  { id: "renault-clio-v-rs-line", brand: "Renault", model: "Clio V", trim: "RS Line", category: "car", segment: "citadine", yearStart: 2019, msrpEur: 23500, fuel: "hybride", power: 145 },
  { id: "renault-clio-iv-rs", brand: "Renault", model: "Clio IV RS", trim: "Trophy", category: "car", segment: "sportive", yearStart: 2013, yearEnd: 2019, msrpEur: 28500, fuel: "essence", power: 220 },
  { id: "renault-megane-iv-gt-line", brand: "Renault", model: "Megane IV", trim: "GT Line", category: "car", segment: "compacte", yearStart: 2016, yearEnd: 2022, msrpEur: 27500, fuel: "essence", power: 140 },
  { id: "renault-megane-iv-rs", brand: "Renault", model: "Megane IV RS", category: "car", segment: "sportive", yearStart: 2018, yearEnd: 2023, msrpEur: 41500, fuel: "essence", power: 280 },
  { id: "renault-megane-iv-rs-trophy-r", brand: "Renault", model: "Megane IV RS", trim: "Trophy-R", category: "car", segment: "sportive", yearStart: 2019, yearEnd: 2020, msrpEur: 71500, fuel: "essence", power: 300, iconic: true },
  { id: "renault-megane-e-tech-equilibre", brand: "Renault", model: "Megane E-Tech", trim: "Equilibre", category: "car", segment: "compacte", yearStart: 2022, msrpEur: 38000, fuel: "elec", power: 220 },
  { id: "renault-captur-ii-zen", brand: "Renault", model: "Captur II", trim: "Zen", category: "car", segment: "suv-compact", yearStart: 2019, msrpEur: 22000, fuel: "essence", power: 100 },
  { id: "renault-captur-ii-rs-line", brand: "Renault", model: "Captur II", trim: "RS Line", category: "car", segment: "suv-compact", yearStart: 2019, msrpEur: 30500, fuel: "phev", power: 160 },
  { id: "renault-arkana-rs-line", brand: "Renault", model: "Arkana", trim: "RS Line", category: "car", segment: "suv-compact", yearStart: 2021, msrpEur: 32500, fuel: "hybride", power: 145 },
  { id: "renault-austral-techno", brand: "Renault", model: "Austral", trim: "Techno", category: "car", segment: "suv-compact", yearStart: 2022, msrpEur: 38500, fuel: "hybride", power: 200 },
  { id: "renault-scenic-iv", brand: "Renault", model: "Scenic IV", trim: "Intens", category: "car", segment: "ludospace", yearStart: 2016, yearEnd: 2022, msrpEur: 30500, fuel: "diesel", power: 130 },
  { id: "renault-zoe", brand: "Renault", model: "Zoe", trim: "Zen R110", category: "car", segment: "citadine", yearStart: 2019, yearEnd: 2024, msrpEur: 32000, fuel: "elec", power: 110 },
  { id: "renault-r5-techno", brand: "Renault", model: "R5 E-Tech", trim: "Techno", category: "car", segment: "citadine", yearStart: 2024, msrpEur: 30500, fuel: "elec", power: 150 },

  // ========= Citroën / DS =========
  { id: "citroen-c1-feel-ii", brand: "Citroën", model: "C1 II", trim: "Feel", category: "car", segment: "citadine", yearStart: 2014, yearEnd: 2022, msrpEur: 11500, fuel: "essence", power: 72 },
  { id: "citroen-c3-feel-iii", brand: "Citroën", model: "C3 III", trim: "Feel", category: "car", segment: "citadine", yearStart: 2016, msrpEur: 17500, fuel: "essence", power: 83 },
  { id: "citroen-c4-feel-iii", brand: "Citroën", model: "C4 III", trim: "Feel", category: "car", segment: "compacte", yearStart: 2020, msrpEur: 25500, fuel: "essence", power: 100 },
  { id: "citroen-c5-x-shine", brand: "Citroën", model: "C5 X", trim: "Shine", category: "car", segment: "berline", yearStart: 2021, msrpEur: 41500, fuel: "phev", power: 225 },
  { id: "citroen-c5-aircross-shine", brand: "Citroën", model: "C5 Aircross", trim: "Shine", category: "car", segment: "suv-compact", yearStart: 2019, msrpEur: 35500, fuel: "phev", power: 225 },
  { id: "citroen-berlingo-iii", brand: "Citroën", model: "Berlingo III", trim: "Feel", category: "car", segment: "ludospace", yearStart: 2018, msrpEur: 24500, fuel: "diesel", power: 100 },
  { id: "ds-3-crossback-perfo", brand: "DS", model: "DS 3 Crossback", trim: "Performance Line", category: "car", segment: "suv-compact", yearStart: 2019, yearEnd: 2023, msrpEur: 32500, fuel: "essence", power: 130 },
  { id: "ds-4-rivoli-ii", brand: "DS", model: "DS 4 II", trim: "Rivoli", category: "car", segment: "compacte", yearStart: 2021, msrpEur: 41500, fuel: "phev", power: 225 },
  { id: "ds-7-crossback-rivoli", brand: "DS", model: "DS 7 Crossback", trim: "Rivoli", category: "car", segment: "suv-compact", yearStart: 2017, msrpEur: 49500, fuel: "phev", power: 300 },

  // ========= Volkswagen =========
  { id: "vw-up-move", brand: "Volkswagen", model: "Up", trim: "Move", category: "car", segment: "citadine", yearStart: 2012, yearEnd: 2023, msrpEur: 14000, fuel: "essence", power: 60 },
  { id: "vw-polo-life-vi", brand: "Volkswagen", model: "Polo VI", trim: "Life", category: "car", segment: "citadine", yearStart: 2017, msrpEur: 21000, fuel: "essence", power: 95 },
  { id: "vw-polo-gti-vi", brand: "Volkswagen", model: "Polo VI GTI", category: "car", segment: "sportive", yearStart: 2018, msrpEur: 31500, fuel: "essence", power: 207 },
  { id: "vw-golf-life-viii", brand: "Volkswagen", model: "Golf VIII", trim: "Life", category: "car", segment: "compacte", yearStart: 2020, msrpEur: 28500, fuel: "essence", power: 130 },
  { id: "vw-golf-style-viii", brand: "Volkswagen", model: "Golf VIII", trim: "Style", category: "car", segment: "compacte", yearStart: 2020, msrpEur: 35000, fuel: "essence", power: 150 },
  { id: "vw-golf-gti-viii", brand: "Volkswagen", model: "Golf VIII GTI", category: "car", segment: "sportive", yearStart: 2020, msrpEur: 47500, fuel: "essence", power: 245 },
  { id: "vw-golf-r-viii", brand: "Volkswagen", model: "Golf VIII R", category: "car", segment: "sportive", yearStart: 2020, msrpEur: 60000, fuel: "essence", power: 320 },
  { id: "vw-golf-gti-vii", brand: "Volkswagen", model: "Golf VII GTI", trim: "Performance", category: "car", segment: "sportive", yearStart: 2013, yearEnd: 2019, msrpEur: 38500, fuel: "essence", power: 245 },
  { id: "vw-tiguan-elegance-iii", brand: "Volkswagen", model: "Tiguan III", trim: "Elegance", category: "car", segment: "suv-compact", yearStart: 2024, msrpEur: 49500, fuel: "phev", power: 204 },
  { id: "vw-t-roc-style", brand: "Volkswagen", model: "T-Roc", trim: "Style", category: "car", segment: "suv-compact", yearStart: 2017, msrpEur: 31000, fuel: "essence", power: 150 },
  { id: "vw-id3-pro", brand: "Volkswagen", model: "ID.3", trim: "Pro", category: "car", segment: "compacte", yearStart: 2020, msrpEur: 39500, fuel: "elec", power: 204 },
  { id: "vw-id4-pro", brand: "Volkswagen", model: "ID.4", trim: "Pro", category: "car", segment: "suv-compact", yearStart: 2021, msrpEur: 47500, fuel: "elec", power: 204 },
  { id: "vw-passat-elegance-b9", brand: "Volkswagen", model: "Passat B9", trim: "Elegance", category: "car", segment: "berline", yearStart: 2024, msrpEur: 47000, fuel: "phev", power: 204 },

  // ========= Audi =========
  { id: "audi-a1-sportback-sline", brand: "Audi", model: "A1 Sportback", trim: "S line", category: "car", segment: "citadine", yearStart: 2018, msrpEur: 28500, fuel: "essence", power: 116 },
  { id: "audi-a3-sportback-sline-iv", brand: "Audi", model: "A3 Sportback IV", trim: "S line", category: "car", segment: "compacte", yearStart: 2020, msrpEur: 38500, fuel: "essence", power: 150 },
  { id: "audi-s3-iv", brand: "Audi", model: "S3 IV", category: "car", segment: "sportive", yearStart: 2020, msrpEur: 56500, fuel: "essence", power: 310 },
  { id: "audi-rs3-iv", brand: "Audi", model: "RS3 IV", category: "car", segment: "sportive", yearStart: 2021, msrpEur: 75500, fuel: "essence", power: 400, iconic: true },
  { id: "audi-rs3-8v", brand: "Audi", model: "RS3 8V", category: "car", segment: "sportive", yearStart: 2015, yearEnd: 2020, msrpEur: 64500, fuel: "essence", power: 400 },
  { id: "audi-a4-avant-sline-b9", brand: "Audi", model: "A4 Avant B9", trim: "S line", category: "car", segment: "break", yearStart: 2015, yearEnd: 2024, msrpEur: 48500, fuel: "diesel", power: 190 },
  { id: "audi-a6-avant-sline-c8", brand: "Audi", model: "A6 Avant C8", trim: "S line", category: "car", segment: "break", yearStart: 2018, msrpEur: 64500, fuel: "diesel", power: 245 },
  { id: "audi-rs6-avant-c8", brand: "Audi", model: "RS6 Avant C8", category: "car", segment: "sportive", yearStart: 2019, msrpEur: 132000, fuel: "essence", power: 600, iconic: true },
  { id: "audi-q3-sline-ii", brand: "Audi", model: "Q3 II", trim: "S line", category: "car", segment: "suv-compact", yearStart: 2018, msrpEur: 41500, fuel: "essence", power: 150 },
  { id: "audi-q5-sline-fy", brand: "Audi", model: "Q5 II", trim: "S line", category: "car", segment: "suv-compact", yearStart: 2017, msrpEur: 56500, fuel: "diesel", power: 204 },
  { id: "audi-tt-rs-iii", brand: "Audi", model: "TT RS III", category: "car", segment: "sportive", yearStart: 2016, yearEnd: 2023, msrpEur: 75500, fuel: "essence", power: 400, iconic: true },
  { id: "audi-r8-v10-perfo", brand: "Audi", model: "R8 V10 Performance", category: "car", segment: "supercar", yearStart: 2019, msrpEur: 195000, fuel: "essence", power: 620, iconic: true },
  { id: "audi-e-tron-gt", brand: "Audi", model: "e-tron GT", category: "car", segment: "premium", yearStart: 2021, msrpEur: 105000, fuel: "elec", power: 530 },

  // ========= BMW =========
  { id: "bmw-118i-f40", brand: "BMW", model: "Série 1 F40", trim: "118i", category: "car", segment: "compacte", yearStart: 2019, msrpEur: 33500, fuel: "essence", power: 140 },
  { id: "bmw-m135i-f40", brand: "BMW", model: "Série 1 F40", trim: "M135i xDrive", category: "car", segment: "sportive", yearStart: 2019, msrpEur: 56500, fuel: "essence", power: 306 },
  { id: "bmw-m140i-f20", brand: "BMW", model: "Série 1 F20", trim: "M140i", category: "car", segment: "sportive", yearStart: 2016, yearEnd: 2019, msrpEur: 49500, fuel: "essence", power: 340, iconic: true },
  { id: "bmw-m2-f87", brand: "BMW", model: "M2 F87", category: "car", segment: "sportive", yearStart: 2016, yearEnd: 2021, msrpEur: 62500, fuel: "essence", power: 370, iconic: true },
  { id: "bmw-m2-g87", brand: "BMW", model: "M2 G87", category: "car", segment: "sportive", yearStart: 2023, msrpEur: 84500, fuel: "essence", power: 460, iconic: true },
  { id: "bmw-320d-g20", brand: "BMW", model: "Série 3 G20", trim: "320d", category: "car", segment: "berline", yearStart: 2018, msrpEur: 49500, fuel: "diesel", power: 190 },
  { id: "bmw-330e-g20", brand: "BMW", model: "Série 3 G20", trim: "330e", category: "car", segment: "berline", yearStart: 2019, msrpEur: 53500, fuel: "phev", power: 292 },
  { id: "bmw-m3-g80-comp", brand: "BMW", model: "M3 G80", trim: "Competition", category: "car", segment: "sportive", yearStart: 2021, msrpEur: 105000, fuel: "essence", power: 510, iconic: true },
  { id: "bmw-m3-f80-comp", brand: "BMW", model: "M3 F80", trim: "Competition", category: "car", segment: "sportive", yearStart: 2014, yearEnd: 2018, msrpEur: 92500, fuel: "essence", power: 450, iconic: true },
  { id: "bmw-m4-f82", brand: "BMW", model: "M4 F82", category: "car", segment: "sportive", yearStart: 2014, yearEnd: 2020, msrpEur: 90500, fuel: "essence", power: 431, iconic: true },
  { id: "bmw-m4-g82-comp", brand: "BMW", model: "M4 G82", trim: "Competition", category: "car", segment: "sportive", yearStart: 2021, msrpEur: 115000, fuel: "essence", power: 510, iconic: true },
  { id: "bmw-540i-g30", brand: "BMW", model: "Série 5 G30", trim: "540i", category: "car", segment: "berline", yearStart: 2017, yearEnd: 2023, msrpEur: 64500, fuel: "essence", power: 340 },
  { id: "bmw-m5-f90-comp", brand: "BMW", model: "M5 F90", trim: "Competition", category: "car", segment: "sportive", yearStart: 2018, msrpEur: 142000, fuel: "essence", power: 625, iconic: true },
  { id: "bmw-x1-xline-u11", brand: "BMW", model: "X1 U11", trim: "xLine", category: "car", segment: "suv-compact", yearStart: 2022, msrpEur: 49500, fuel: "essence", power: 156 },
  { id: "bmw-x3-xdrive30e-g01", brand: "BMW", model: "X3 G01", trim: "xDrive30e", category: "car", segment: "suv-compact", yearStart: 2017, yearEnd: 2024, msrpEur: 68500, fuel: "phev", power: 292 },
  { id: "bmw-x5-xdrive45e-g05", brand: "BMW", model: "X5 G05", trim: "xDrive45e", category: "car", segment: "suv-large", yearStart: 2018, msrpEur: 82500, fuel: "phev", power: 394 },
  { id: "bmw-i4-edrive40", brand: "BMW", model: "i4", trim: "eDrive40", category: "car", segment: "berline", yearStart: 2021, msrpEur: 57500, fuel: "elec", power: 340 },
  { id: "bmw-ix-xdrive40", brand: "BMW", model: "iX", trim: "xDrive40", category: "car", segment: "suv-large", yearStart: 2021, msrpEur: 86500, fuel: "elec", power: 326 },
  { id: "bmw-z4-m40i-g29", brand: "BMW", model: "Z4 G29", trim: "M40i", category: "car", segment: "sportive", yearStart: 2018, msrpEur: 70500, fuel: "essence", power: 340 },

  // ========= Mercedes =========
  { id: "mb-a200-w177", brand: "Mercedes", model: "Classe A W177", trim: "A 200", category: "car", segment: "compacte", yearStart: 2018, msrpEur: 35500, fuel: "essence", power: 163 },
  { id: "mb-a35-amg-w177", brand: "Mercedes", model: "A 35 AMG W177", category: "car", segment: "sportive", yearStart: 2019, msrpEur: 56500, fuel: "essence", power: 306 },
  { id: "mb-a45-s-amg-w177", brand: "Mercedes", model: "A 45 S AMG W177", category: "car", segment: "sportive", yearStart: 2019, msrpEur: 75000, fuel: "essence", power: 421, iconic: true },
  { id: "mb-c220d-w205", brand: "Mercedes", model: "Classe C W205", trim: "C 220 d", category: "car", segment: "berline", yearStart: 2014, yearEnd: 2021, msrpEur: 47500, fuel: "diesel", power: 194 },
  { id: "mb-c300-w206", brand: "Mercedes", model: "Classe C W206", trim: "C 300", category: "car", segment: "berline", yearStart: 2021, msrpEur: 56500, fuel: "essence", power: 258 },
  { id: "mb-c63-amg-w205", brand: "Mercedes", model: "C 63 AMG W205", category: "car", segment: "sportive", yearStart: 2015, yearEnd: 2021, msrpEur: 88500, fuel: "essence", power: 510, iconic: true },
  { id: "mb-e220d-w213", brand: "Mercedes", model: "Classe E W213", trim: "E 220 d", category: "car", segment: "berline", yearStart: 2016, yearEnd: 2024, msrpEur: 60500, fuel: "diesel", power: 194 },
  { id: "mb-glc-300e-x254", brand: "Mercedes", model: "GLC X254", trim: "300 e", category: "car", segment: "suv-compact", yearStart: 2022, msrpEur: 73500, fuel: "phev", power: 313 },
  { id: "mb-amg-gt-c190", brand: "Mercedes", model: "AMG GT C190", trim: "GT", category: "car", segment: "supercar", yearStart: 2014, yearEnd: 2021, msrpEur: 130000, fuel: "essence", power: 476, iconic: true },
  { id: "mb-amg-gt-r-c190", brand: "Mercedes", model: "AMG GT R C190", category: "car", segment: "supercar", yearStart: 2017, yearEnd: 2021, msrpEur: 175000, fuel: "essence", power: 585, iconic: true },
  { id: "mb-eqe-350-v295", brand: "Mercedes", model: "EQE V295", trim: "350+", category: "car", segment: "berline", yearStart: 2022, msrpEur: 75500, fuel: "elec", power: 292 },

  // ========= Porsche =========
  { id: "porsche-718-cayman-base", brand: "Porsche", model: "718 Cayman", category: "car", segment: "sportive", yearStart: 2016, msrpEur: 64500, fuel: "essence", power: 300, iconic: true },
  { id: "porsche-718-cayman-gts-4", brand: "Porsche", model: "718 Cayman GTS 4.0", category: "car", segment: "sportive", yearStart: 2020, msrpEur: 95500, fuel: "essence", power: 400, iconic: true },
  { id: "porsche-718-cayman-gt4", brand: "Porsche", model: "718 Cayman GT4", category: "car", segment: "supercar", yearStart: 2019, msrpEur: 105000, fuel: "essence", power: 420, iconic: true },
  { id: "porsche-911-carrera-992", brand: "Porsche", model: "911 992", trim: "Carrera", category: "car", segment: "supercar", yearStart: 2019, msrpEur: 120000, fuel: "essence", power: 385, iconic: true },
  { id: "porsche-911-carrera-s-992", brand: "Porsche", model: "911 992", trim: "Carrera S", category: "car", segment: "supercar", yearStart: 2019, msrpEur: 138000, fuel: "essence", power: 450, iconic: true },
  { id: "porsche-911-gt3-992", brand: "Porsche", model: "911 992", trim: "GT3", category: "car", segment: "supercar", yearStart: 2021, msrpEur: 175000, fuel: "essence", power: 510, iconic: true },
  { id: "porsche-911-turbo-s-992", brand: "Porsche", model: "911 992", trim: "Turbo S", category: "car", segment: "supercar", yearStart: 2020, msrpEur: 230000, fuel: "essence", power: 650, iconic: true },
  { id: "porsche-macan-base", brand: "Porsche", model: "Macan", category: "car", segment: "premium", yearStart: 2014, msrpEur: 65500, fuel: "essence", power: 265 },
  { id: "porsche-macan-gts", brand: "Porsche", model: "Macan", trim: "GTS", category: "car", segment: "premium", yearStart: 2016, msrpEur: 95500, fuel: "essence", power: 380 },
  { id: "porsche-cayenne-e-hybrid", brand: "Porsche", model: "Cayenne", trim: "E-Hybrid", category: "car", segment: "premium", yearStart: 2018, msrpEur: 95500, fuel: "phev", power: 462 },
  { id: "porsche-taycan-4s", brand: "Porsche", model: "Taycan", trim: "4S", category: "car", segment: "premium", yearStart: 2019, msrpEur: 110000, fuel: "elec", power: 530 },
  { id: "porsche-taycan-turbo-s", brand: "Porsche", model: "Taycan", trim: "Turbo S", category: "car", segment: "premium", yearStart: 2019, msrpEur: 195000, fuel: "elec", power: 761, iconic: true },

  // ========= Toyota =========
  { id: "toyota-aygo-x", brand: "Toyota", model: "Aygo X", trim: "Pulse", category: "car", segment: "citadine", yearStart: 2022, msrpEur: 18500, fuel: "essence", power: 72 },
  { id: "toyota-yaris-iv-design", brand: "Toyota", model: "Yaris IV", trim: "Design", category: "car", segment: "citadine", yearStart: 2020, msrpEur: 23500, fuel: "hybride", power: 116 },
  { id: "toyota-yaris-cross", brand: "Toyota", model: "Yaris Cross", trim: "Design", category: "car", segment: "suv-compact", yearStart: 2021, msrpEur: 26500, fuel: "hybride", power: 116 },
  { id: "toyota-gr-yaris", brand: "Toyota", model: "GR Yaris", category: "car", segment: "sportive", yearStart: 2020, msrpEur: 39500, fuel: "essence", power: 261, iconic: true },
  { id: "toyota-gr-yaris-mpr-2024", brand: "Toyota", model: "GR Yaris", trim: "Mise à jour 2024", category: "car", segment: "sportive", yearStart: 2024, msrpEur: 51500, fuel: "essence", power: 280, iconic: true },
  { id: "toyota-corolla-design-12", brand: "Toyota", model: "Corolla XII", trim: "Design", category: "car", segment: "compacte", yearStart: 2018, msrpEur: 28500, fuel: "hybride", power: 122 },
  { id: "toyota-corolla-touring-gr-sport", brand: "Toyota", model: "Corolla Touring", trim: "GR Sport", category: "car", segment: "break", yearStart: 2019, msrpEur: 32500, fuel: "hybride", power: 184 },
  { id: "toyota-c-hr-ii-design", brand: "Toyota", model: "C-HR II", trim: "Design", category: "car", segment: "suv-compact", yearStart: 2023, msrpEur: 33500, fuel: "hybride", power: 140 },
  { id: "toyota-rav4-v-design", brand: "Toyota", model: "RAV4 V", trim: "Design", category: "car", segment: "suv-compact", yearStart: 2018, msrpEur: 38500, fuel: "hybride", power: 218 },
  { id: "toyota-rav4-phev-collection", brand: "Toyota", model: "RAV4 PHEV", trim: "Collection", category: "car", segment: "suv-compact", yearStart: 2020, msrpEur: 58500, fuel: "phev", power: 306 },
  { id: "toyota-prius-v-design", brand: "Toyota", model: "Prius V", trim: "Design", category: "car", segment: "compacte", yearStart: 2023, msrpEur: 41500, fuel: "phev", power: 223 },
  { id: "toyota-gr-supra-2.0", brand: "Toyota", model: "GR Supra A90", trim: "2.0L", category: "car", segment: "sportive", yearStart: 2020, msrpEur: 56500, fuel: "essence", power: 258, iconic: true },
  { id: "toyota-gr-supra-3.0", brand: "Toyota", model: "GR Supra A90", trim: "3.0L", category: "car", segment: "sportive", yearStart: 2019, msrpEur: 67500, fuel: "essence", power: 340, iconic: true },
  { id: "toyota-gr-supra-3.0-mt", brand: "Toyota", model: "GR Supra A90", trim: "3.0L MT", category: "car", segment: "sportive", yearStart: 2022, msrpEur: 71500, fuel: "essence", power: 340, iconic: true },
  { id: "toyota-gr86", brand: "Toyota", model: "GR86", category: "car", segment: "sportive", yearStart: 2022, msrpEur: 35500, fuel: "essence", power: 234, iconic: true },
  { id: "toyota-gt86", brand: "Toyota", model: "GT86", category: "car", segment: "sportive", yearStart: 2012, yearEnd: 2020, msrpEur: 31500, fuel: "essence", power: 200, iconic: true },
  { id: "toyota-mr2-w30", brand: "Toyota", model: "MR2 W30", category: "car", segment: "sportive", yearStart: 1999, yearEnd: 2007, msrpEur: 28500, fuel: "essence", power: 140, iconic: true },
  { id: "toyota-hilux-invincible", brand: "Toyota", model: "Hilux", trim: "Invincible", category: "car", segment: "utilitaire", yearStart: 2020, msrpEur: 47500, fuel: "diesel", power: 204 },
  { id: "toyota-land-cruiser-300", brand: "Toyota", model: "Land Cruiser J300", category: "car", segment: "suv-large", yearStart: 2021, msrpEur: 88500, fuel: "diesel", power: 305, iconic: true },

  // ========= Mazda =========
  { id: "mazda-2-iv", brand: "Mazda", model: "Mazda2 IV", trim: "Centre-Line", category: "car", segment: "citadine", yearStart: 2014, msrpEur: 18500, fuel: "essence", power: 90 },
  { id: "mazda-2-hybrid", brand: "Mazda", model: "Mazda2 Hybrid", category: "car", segment: "citadine", yearStart: 2022, msrpEur: 23500, fuel: "hybride", power: 116 },
  { id: "mazda-3-iv-skyactiv-x", brand: "Mazda", model: "Mazda3 IV", trim: "Skyactiv-X 186", category: "car", segment: "compacte", yearStart: 2019, msrpEur: 32500, fuel: "essence", power: 186 },
  { id: "mazda-3-iv-base", brand: "Mazda", model: "Mazda3 IV", trim: "Centre-Line", category: "car", segment: "compacte", yearStart: 2019, msrpEur: 26500, fuel: "essence", power: 122 },
  { id: "mazda-3-mps-bk", brand: "Mazda", model: "Mazda3 MPS BK", category: "car", segment: "sportive", yearStart: 2006, yearEnd: 2009, msrpEur: 27500, fuel: "essence", power: 260, iconic: true },
  { id: "mazda-6-iii-skyactiv-d", brand: "Mazda", model: "Mazda6 III", trim: "Skyactiv-D", category: "car", segment: "berline", yearStart: 2012, yearEnd: 2024, msrpEur: 35500, fuel: "diesel", power: 184 },
  { id: "mazda-6-tourer-iii", brand: "Mazda", model: "Mazda6 Tourer", trim: "Skyactiv-G", category: "car", segment: "break", yearStart: 2012, yearEnd: 2024, msrpEur: 36500, fuel: "essence", power: 165 },
  { id: "mazda-mx-5-nd-1.5", brand: "Mazda", model: "MX-5 ND", trim: "1.5L Skyactiv-G", category: "car", segment: "sportive", yearStart: 2015, msrpEur: 28500, fuel: "essence", power: 132, iconic: true },
  { id: "mazda-mx-5-nd-2.0", brand: "Mazda", model: "MX-5 ND", trim: "2.0L Skyactiv-G", category: "car", segment: "sportive", yearStart: 2018, msrpEur: 32500, fuel: "essence", power: 184, iconic: true },
  { id: "mazda-mx-5-nc", brand: "Mazda", model: "MX-5 NC", category: "car", segment: "sportive", yearStart: 2005, yearEnd: 2015, msrpEur: 25500, fuel: "essence", power: 160, iconic: true },
  { id: "mazda-mx-5-nb", brand: "Mazda", model: "MX-5 NB", category: "car", segment: "sportive", yearStart: 1998, yearEnd: 2005, msrpEur: 22500, fuel: "essence", power: 140, iconic: true },
  { id: "mazda-rx-7-fd", brand: "Mazda", model: "RX-7 FD", category: "car", segment: "sportive", yearStart: 1992, yearEnd: 2002, msrpEur: 35000, fuel: "essence", power: 280, iconic: true },
  { id: "mazda-rx-8-r3", brand: "Mazda", model: "RX-8", trim: "R3", category: "car", segment: "sportive", yearStart: 2008, yearEnd: 2012, msrpEur: 32500, fuel: "essence", power: 232, iconic: true },
  { id: "mazda-cx-3-iv", brand: "Mazda", model: "CX-3", trim: "Centre-Line", category: "car", segment: "suv-compact", yearStart: 2015, yearEnd: 2021, msrpEur: 22500, fuel: "essence", power: 121 },
  { id: "mazda-cx-30-skyactiv-x", brand: "Mazda", model: "CX-30", trim: "Skyactiv-X", category: "car", segment: "suv-compact", yearStart: 2019, msrpEur: 33500, fuel: "essence", power: 186 },
  { id: "mazda-cx-30-base", brand: "Mazda", model: "CX-30", trim: "Centre-Line", category: "car", segment: "suv-compact", yearStart: 2019, msrpEur: 27500, fuel: "essence", power: 122 },
  { id: "mazda-cx-5-ii-base", brand: "Mazda", model: "CX-5 II", trim: "Centre-Line", category: "car", segment: "suv-compact", yearStart: 2017, msrpEur: 32500, fuel: "essence", power: 165 },
  { id: "mazda-cx-5-ii-takumi", brand: "Mazda", model: "CX-5 II", trim: "Takumi", category: "car", segment: "suv-compact", yearStart: 2017, msrpEur: 41500, fuel: "diesel", power: 184 },
  { id: "mazda-cx-60-takumi", brand: "Mazda", model: "CX-60", trim: "Takumi", category: "car", segment: "suv-compact", yearStart: 2022, msrpEur: 56500, fuel: "phev", power: 327 },
  { id: "mazda-cx-60-homura", brand: "Mazda", model: "CX-60", trim: "Homura", category: "car", segment: "suv-compact", yearStart: 2022, msrpEur: 53500, fuel: "diesel", power: 254 },
  { id: "mazda-mx-30-elec", brand: "Mazda", model: "MX-30", trim: "First Edition", category: "car", segment: "suv-compact", yearStart: 2020, msrpEur: 35500, fuel: "elec", power: 145 },
  { id: "mazda-mx-30-r-ev", brand: "Mazda", model: "MX-30 R-EV", category: "car", segment: "suv-compact", yearStart: 2023, msrpEur: 38500, fuel: "phev", power: 170 },

  // ========= Honda / Nissan / Subaru / Mitsubishi =========
  { id: "honda-jazz-iv-hybrid", brand: "Honda", model: "Jazz IV", trim: "e:HEV", category: "car", segment: "citadine", yearStart: 2020, msrpEur: 24500, fuel: "hybride", power: 109 },
  { id: "honda-civic-xi-hybrid", brand: "Honda", model: "Civic XI", trim: "e:HEV", category: "car", segment: "compacte", yearStart: 2022, msrpEur: 35500, fuel: "hybride", power: 184 },
  { id: "honda-civic-x-type-r-fk8", brand: "Honda", model: "Civic Type R FK8", category: "car", segment: "sportive", yearStart: 2017, yearEnd: 2021, msrpEur: 41500, fuel: "essence", power: 320, iconic: true },
  { id: "honda-civic-xi-type-r-fl5", brand: "Honda", model: "Civic Type R FL5", category: "car", segment: "sportive", yearStart: 2023, msrpEur: 56500, fuel: "essence", power: 329, iconic: true },
  { id: "honda-hr-v-iii-hybrid", brand: "Honda", model: "HR-V III", trim: "e:HEV", category: "car", segment: "suv-compact", yearStart: 2022, msrpEur: 32500, fuel: "hybride", power: 131 },
  { id: "honda-cr-v-vi-hybrid", brand: "Honda", model: "CR-V VI", trim: "e:HEV", category: "car", segment: "suv-compact", yearStart: 2023, msrpEur: 51500, fuel: "hybride", power: 184 },
  { id: "honda-s2000-ap2", brand: "Honda", model: "S2000 AP2", category: "car", segment: "sportive", yearStart: 2003, yearEnd: 2009, msrpEur: 38500, fuel: "essence", power: 240, iconic: true },
  { id: "honda-nsx-na1", brand: "Honda", model: "NSX NA1", category: "car", segment: "supercar", yearStart: 1990, yearEnd: 2005, msrpEur: 85000, fuel: "essence", power: 274, iconic: true },
  { id: "nissan-micra-k14", brand: "Nissan", model: "Micra K14", trim: "Acenta", category: "car", segment: "citadine", yearStart: 2017, yearEnd: 2024, msrpEur: 17500, fuel: "essence", power: 92 },
  { id: "nissan-juke-ii", brand: "Nissan", model: "Juke II", trim: "N-Connecta", category: "car", segment: "suv-compact", yearStart: 2019, msrpEur: 26500, fuel: "essence", power: 117 },
  { id: "nissan-qashqai-iii-tekna", brand: "Nissan", model: "Qashqai III", trim: "Tekna", category: "car", segment: "suv-compact", yearStart: 2021, msrpEur: 38500, fuel: "hybride", power: 190 },
  { id: "nissan-x-trail-iv", brand: "Nissan", model: "X-Trail IV", trim: "Tekna", category: "car", segment: "suv-large", yearStart: 2022, msrpEur: 48500, fuel: "hybride", power: 213 },
  { id: "nissan-leaf-ii", brand: "Nissan", model: "Leaf II", trim: "Tekna", category: "car", segment: "compacte", yearStart: 2017, msrpEur: 35500, fuel: "elec", power: 150 },
  { id: "nissan-gt-r-r35", brand: "Nissan", model: "GT-R R35", category: "car", segment: "supercar", yearStart: 2007, yearEnd: 2024, msrpEur: 105000, fuel: "essence", power: 570, iconic: true },
  { id: "nissan-370z", brand: "Nissan", model: "370Z", category: "car", segment: "sportive", yearStart: 2009, yearEnd: 2020, msrpEur: 38500, fuel: "essence", power: 328, iconic: true },
  { id: "nissan-skyline-r34-gtr", brand: "Nissan", model: "Skyline R34 GT-R", category: "car", segment: "sportive", yearStart: 1999, yearEnd: 2002, msrpEur: 65000, fuel: "essence", power: 280, iconic: true },
  { id: "subaru-impreza-wrx-sti-grb", brand: "Subaru", model: "Impreza WRX STI GRB", category: "car", segment: "sportive", yearStart: 2008, yearEnd: 2014, msrpEur: 45500, fuel: "essence", power: 300, iconic: true },
  { id: "subaru-brz-zd8", brand: "Subaru", model: "BRZ ZD8", category: "car", segment: "sportive", yearStart: 2022, msrpEur: 38500, fuel: "essence", power: 234, iconic: true },
  { id: "subaru-forester-v-hybrid", brand: "Subaru", model: "Forester V", trim: "e-Boxer", category: "car", segment: "suv-compact", yearStart: 2019, msrpEur: 42500, fuel: "hybride", power: 150 },
  { id: "mitsubishi-lancer-evo-x", brand: "Mitsubishi", model: "Lancer Evo X", trim: "FQ-360", category: "car", segment: "sportive", yearStart: 2008, yearEnd: 2016, msrpEur: 52500, fuel: "essence", power: 360, iconic: true },

  // ========= Tesla =========
  { id: "tesla-model-3-rwd", brand: "Tesla", model: "Model 3", trim: "RWD", category: "car", segment: "berline", yearStart: 2019, msrpEur: 42500, fuel: "elec", power: 283 },
  { id: "tesla-model-3-lr", brand: "Tesla", model: "Model 3", trim: "Long Range", category: "car", segment: "berline", yearStart: 2019, msrpEur: 51500, fuel: "elec", power: 351 },
  { id: "tesla-model-3-perfo", brand: "Tesla", model: "Model 3", trim: "Performance", category: "car", segment: "sportive", yearStart: 2019, msrpEur: 60500, fuel: "elec", power: 460 },
  { id: "tesla-model-y-rwd", brand: "Tesla", model: "Model Y", trim: "RWD", category: "car", segment: "suv-compact", yearStart: 2022, msrpEur: 45500, fuel: "elec", power: 299 },
  { id: "tesla-model-y-lr", brand: "Tesla", model: "Model Y", trim: "Long Range", category: "car", segment: "suv-compact", yearStart: 2022, msrpEur: 53500, fuel: "elec", power: 384 },
  { id: "tesla-model-y-perfo", brand: "Tesla", model: "Model Y", trim: "Performance", category: "car", segment: "suv-compact", yearStart: 2022, msrpEur: 62500, fuel: "elec", power: 460 },
  { id: "tesla-model-s-plaid", brand: "Tesla", model: "Model S", trim: "Plaid", category: "car", segment: "premium", yearStart: 2021, msrpEur: 138000, fuel: "elec", power: 1020, iconic: true },

  // ========= Fiat / Alfa =========
  { id: "fiat-500-iii", brand: "Fiat", model: "500", trim: "Lounge", category: "car", segment: "citadine", yearStart: 2007, yearEnd: 2024, msrpEur: 14500, fuel: "essence", power: 70 },
  { id: "fiat-500e-icon", brand: "Fiat", model: "500e", trim: "Icon", category: "car", segment: "citadine", yearStart: 2020, msrpEur: 32500, fuel: "elec", power: 118 },
  { id: "fiat-500x-cross", brand: "Fiat", model: "500X", trim: "Cross", category: "car", segment: "suv-compact", yearStart: 2014, msrpEur: 23500, fuel: "essence", power: 130 },
  { id: "fiat-panda-iii", brand: "Fiat", model: "Panda III", trim: "Cross", category: "car", segment: "citadine", yearStart: 2011, msrpEur: 16500, fuel: "essence", power: 70 },
  { id: "abarth-595-comp", brand: "Abarth", model: "595", trim: "Competizione", category: "car", segment: "sportive", yearStart: 2016, yearEnd: 2024, msrpEur: 27500, fuel: "essence", power: 180, iconic: true },
  { id: "alfa-giulia-ti", brand: "Alfa Romeo", model: "Giulia", trim: "Ti", category: "car", segment: "berline", yearStart: 2016, msrpEur: 47500, fuel: "essence", power: 280 },
  { id: "alfa-giulia-quadrifoglio", brand: "Alfa Romeo", model: "Giulia", trim: "Quadrifoglio", category: "car", segment: "sportive", yearStart: 2016, msrpEur: 86500, fuel: "essence", power: 510, iconic: true },
  { id: "alfa-stelvio-veloce", brand: "Alfa Romeo", model: "Stelvio", trim: "Veloce", category: "car", segment: "premium", yearStart: 2017, msrpEur: 64500, fuel: "essence", power: 280 },
  { id: "alfa-4c", brand: "Alfa Romeo", model: "4C", category: "car", segment: "sportive", yearStart: 2013, yearEnd: 2020, msrpEur: 65500, fuel: "essence", power: 240, iconic: true },

  // ========= Hyundai / Kia =========
  { id: "hyundai-i10-iii", brand: "Hyundai", model: "i10 III", trim: "Initia", category: "car", segment: "citadine", yearStart: 2020, msrpEur: 16500, fuel: "essence", power: 84 },
  { id: "hyundai-i20-iii-n-line", brand: "Hyundai", model: "i20 III", trim: "N Line", category: "car", segment: "citadine", yearStart: 2020, msrpEur: 25500, fuel: "essence", power: 120 },
  { id: "hyundai-i20-n", brand: "Hyundai", model: "i20 N", category: "car", segment: "sportive", yearStart: 2021, msrpEur: 30500, fuel: "essence", power: 204, iconic: true },
  { id: "hyundai-i30-fastback-n", brand: "Hyundai", model: "i30 N", trim: "Fastback Performance", category: "car", segment: "sportive", yearStart: 2019, msrpEur: 41500, fuel: "essence", power: 280, iconic: true },
  { id: "hyundai-kona-electric", brand: "Hyundai", model: "Kona Electric", trim: "Executive 64kWh", category: "car", segment: "suv-compact", yearStart: 2018, msrpEur: 39500, fuel: "elec", power: 204 },
  { id: "hyundai-tucson-iv-hybrid", brand: "Hyundai", model: "Tucson IV", trim: "Executive Hybrid", category: "car", segment: "suv-compact", yearStart: 2020, msrpEur: 38500, fuel: "hybride", power: 230 },
  { id: "hyundai-ioniq-5", brand: "Hyundai", model: "Ioniq 5", trim: "Executive", category: "car", segment: "suv-compact", yearStart: 2021, msrpEur: 51500, fuel: "elec", power: 217 },
  { id: "hyundai-ioniq-5-n", brand: "Hyundai", model: "Ioniq 5 N", category: "car", segment: "sportive", yearStart: 2024, msrpEur: 78500, fuel: "elec", power: 650, iconic: true },
  { id: "hyundai-ioniq-6", brand: "Hyundai", model: "Ioniq 6", trim: "Executive", category: "car", segment: "berline", yearStart: 2023, msrpEur: 56500, fuel: "elec", power: 229 },
  { id: "kia-picanto-iii-active", brand: "Kia", model: "Picanto III", trim: "Active", category: "car", segment: "citadine", yearStart: 2017, msrpEur: 15500, fuel: "essence", power: 67 },
  { id: "kia-ceed-iii-active", brand: "Kia", model: "Ceed III", trim: "Active", category: "car", segment: "compacte", yearStart: 2018, msrpEur: 24500, fuel: "essence", power: 120 },
  { id: "kia-niro-ev-active", brand: "Kia", model: "Niro EV", trim: "Active", category: "car", segment: "suv-compact", yearStart: 2022, msrpEur: 41500, fuel: "elec", power: 204 },
  { id: "kia-sportage-v-active", brand: "Kia", model: "Sportage V", trim: "Active Hybrid", category: "car", segment: "suv-compact", yearStart: 2021, msrpEur: 39500, fuel: "hybride", power: 230 },
  { id: "kia-ev6-gt-line", brand: "Kia", model: "EV6", trim: "GT-Line", category: "car", segment: "suv-compact", yearStart: 2021, msrpEur: 56500, fuel: "elec", power: 229 },
  { id: "kia-ev6-gt", brand: "Kia", model: "EV6 GT", category: "car", segment: "sportive", yearStart: 2022, msrpEur: 71500, fuel: "elec", power: 585, iconic: true },

  // ========= Mini =========
  { id: "mini-cooper-3p-f56", brand: "Mini", model: "Cooper F56", trim: "3 portes", category: "car", segment: "citadine", yearStart: 2014, yearEnd: 2024, msrpEur: 26500, fuel: "essence", power: 136 },
  { id: "mini-cooper-s-3p-f56", brand: "Mini", model: "Cooper S F56", trim: "3 portes", category: "car", segment: "sportive", yearStart: 2014, yearEnd: 2024, msrpEur: 32500, fuel: "essence", power: 192 },
  { id: "mini-jcw-f56", brand: "Mini", model: "John Cooper Works F56", category: "car", segment: "sportive", yearStart: 2015, yearEnd: 2024, msrpEur: 38500, fuel: "essence", power: 231, iconic: true },
  { id: "mini-countryman-f60-jcw", brand: "Mini", model: "Countryman F60", trim: "John Cooper Works", category: "car", segment: "suv-compact", yearStart: 2017, yearEnd: 2024, msrpEur: 45500, fuel: "essence", power: 306 },

  // ========= Ford / Opel / Skoda / Seat =========
  { id: "ford-fiesta-st-mk8", brand: "Ford", model: "Fiesta ST MK8", category: "car", segment: "sportive", yearStart: 2018, yearEnd: 2023, msrpEur: 27500, fuel: "essence", power: 200, iconic: true },
  { id: "ford-focus-mk4", brand: "Ford", model: "Focus MK4", trim: "ST-Line", category: "car", segment: "compacte", yearStart: 2018, msrpEur: 27500, fuel: "essence", power: 125 },
  { id: "ford-focus-st-mk4", brand: "Ford", model: "Focus ST MK4", category: "car", segment: "sportive", yearStart: 2019, msrpEur: 41500, fuel: "essence", power: 280 },
  { id: "ford-puma-st", brand: "Ford", model: "Puma ST", category: "car", segment: "sportive", yearStart: 2020, msrpEur: 32500, fuel: "essence", power: 200 },
  { id: "ford-mustang-mach1-s550", brand: "Ford", model: "Mustang S550", trim: "Mach 1", category: "car", segment: "sportive", yearStart: 2020, yearEnd: 2023, msrpEur: 65500, fuel: "essence", power: 460, iconic: true },
  { id: "ford-mustang-gt-s650", brand: "Ford", model: "Mustang S650", trim: "GT", category: "car", segment: "sportive", yearStart: 2024, msrpEur: 62500, fuel: "essence", power: 446, iconic: true },
  { id: "opel-corsa-f", brand: "Opel", model: "Corsa F", trim: "Edition", category: "car", segment: "citadine", yearStart: 2019, msrpEur: 19500, fuel: "essence", power: 100 },
  { id: "opel-astra-l", brand: "Opel", model: "Astra L", trim: "Elegance", category: "car", segment: "compacte", yearStart: 2021, msrpEur: 28500, fuel: "essence", power: 130 },
  { id: "skoda-fabia-iv", brand: "Skoda", model: "Fabia IV", trim: "Ambition", category: "car", segment: "citadine", yearStart: 2021, msrpEur: 21500, fuel: "essence", power: 95 },
  { id: "skoda-octavia-iv", brand: "Skoda", model: "Octavia IV", trim: "Ambition", category: "car", segment: "compacte", yearStart: 2020, msrpEur: 28500, fuel: "essence", power: 150 },
  { id: "skoda-octavia-rs-iv", brand: "Skoda", model: "Octavia RS IV", category: "car", segment: "sportive", yearStart: 2020, msrpEur: 41500, fuel: "essence", power: 245 },
  { id: "skoda-kodiaq-ii", brand: "Skoda", model: "Kodiaq II", trim: "Selection", category: "car", segment: "suv-large", yearStart: 2024, msrpEur: 47500, fuel: "phev", power: 204 },
  { id: "seat-leon-iv", brand: "Seat", model: "Leon IV", trim: "FR", category: "car", segment: "compacte", yearStart: 2020, msrpEur: 30500, fuel: "essence", power: 150 },
  { id: "cupra-leon-vz", brand: "Cupra", model: "Leon", trim: "VZ", category: "car", segment: "sportive", yearStart: 2020, msrpEur: 47500, fuel: "essence", power: 300 },
  { id: "cupra-formentor-vz", brand: "Cupra", model: "Formentor", trim: "VZ", category: "car", segment: "suv-compact", yearStart: 2020, msrpEur: 51500, fuel: "essence", power: 310 },
  { id: "cupra-born-77", brand: "Cupra", model: "Born", trim: "77kWh", category: "car", segment: "compacte", yearStart: 2021, msrpEur: 43500, fuel: "elec", power: 231 },

  // ========= Lexus =========
  { id: "lexus-is500-fsport", brand: "Lexus", model: "IS 500", trim: "F Sport", category: "car", segment: "sportive", yearStart: 2022, msrpEur: 78500, fuel: "essence", power: 481, iconic: true },
  { id: "lexus-rc-f", brand: "Lexus", model: "RC F", category: "car", segment: "sportive", yearStart: 2014, msrpEur: 88500, fuel: "essence", power: 477, iconic: true },
  { id: "lexus-lc-500", brand: "Lexus", model: "LC 500", category: "car", segment: "supercar", yearStart: 2017, msrpEur: 115000, fuel: "essence", power: 477, iconic: true },
  { id: "lexus-ux-300e", brand: "Lexus", model: "UX 300e", trim: "Pack", category: "car", segment: "suv-compact", yearStart: 2020, msrpEur: 53500, fuel: "elec", power: 204 },

  // ========= Volvo / Polestar =========
  { id: "volvo-xc40-recharge", brand: "Volvo", model: "XC40 Recharge", trim: "Plus", category: "car", segment: "suv-compact", yearStart: 2020, msrpEur: 50500, fuel: "elec", power: 231 },
  { id: "volvo-xc60-t8", brand: "Volvo", model: "XC60", trim: "T8 Recharge", category: "car", segment: "premium", yearStart: 2017, msrpEur: 76500, fuel: "phev", power: 455 },
  { id: "polestar-2-lr-dual", brand: "Polestar", model: "2", trim: "Long Range Dual Motor", category: "car", segment: "berline", yearStart: 2020, msrpEur: 56500, fuel: "elec", power: 408 },
  { id: "polestar-4-lr-dual", brand: "Polestar", model: "4", trim: "Long Range Dual Motor", category: "car", segment: "premium", yearStart: 2024, msrpEur: 67500, fuel: "elec", power: 544 },

  // ========= Dacia =========
  { id: "dacia-sandero-iii", brand: "Dacia", model: "Sandero III", trim: "Essential", category: "car", segment: "citadine", yearStart: 2020, msrpEur: 12500, fuel: "essence", power: 67 },
  { id: "dacia-duster-iii", brand: "Dacia", model: "Duster III", trim: "Expression", category: "car", segment: "suv-compact", yearStart: 2024, msrpEur: 21500, fuel: "essence", power: 100 },
  { id: "dacia-spring-extreme", brand: "Dacia", model: "Spring", trim: "Extreme", category: "car", segment: "citadine", yearStart: 2021, msrpEur: 21500, fuel: "elec", power: 65 },

  // ========= Ferrari / Lamborghini / autres exotiques =========
  { id: "ferrari-488-gtb", brand: "Ferrari", model: "488 GTB", category: "car", segment: "supercar", yearStart: 2015, yearEnd: 2019, msrpEur: 220000, fuel: "essence", power: 670, iconic: true },
  { id: "ferrari-f8-tributo", brand: "Ferrari", model: "F8 Tributo", category: "car", segment: "supercar", yearStart: 2019, yearEnd: 2023, msrpEur: 245000, fuel: "essence", power: 720, iconic: true },
  { id: "ferrari-296-gtb", brand: "Ferrari", model: "296 GTB", category: "car", segment: "supercar", yearStart: 2022, msrpEur: 280000, fuel: "phev", power: 830, iconic: true },
  { id: "lambo-huracan-evo", brand: "Lamborghini", model: "Huracán Evo", category: "car", segment: "supercar", yearStart: 2019, msrpEur: 235000, fuel: "essence", power: 640, iconic: true },
  { id: "lambo-urus-s", brand: "Lamborghini", model: "Urus", trim: "S", category: "car", segment: "supercar", yearStart: 2022, msrpEur: 245000, fuel: "essence", power: 666, iconic: true },
  { id: "mclaren-720s", brand: "McLaren", model: "720S", category: "car", segment: "supercar", yearStart: 2017, yearEnd: 2023, msrpEur: 270000, fuel: "essence", power: 720, iconic: true },
];
